### ISSUE TITLE
Port svgToPdf to other platforms than OSX

### ISSUE THREAD

**Issue by kaoskorobase** [kaoskorobase/shake-latex#3]
Currently the path to Inkscape is hardcoded in `svgToPdf` and it's specific to OSX.

One possibility to fix that is to provide a function `svgToPdfWithOptions` that allows to pass the path to Inkscape explicitly. `svgToPdf` could then use a different default path for each operating system: `/Applications/Inkscape.app/Contents/Resources/bin/inkscape` on OSX, `inkscape` on Linux and something sensible on Windows.

**Comment by svenkeidel** [comment]
Why not just `inkscape` and tell the user, that inkscape has to be in the `PATH`? Hard coding these paths is not the most reliable solution IMHO.

**Comment by kaoskorobase** [comment]
You're right, that's why I proposed `svgToPdfWithOption` where you can pass an executable, with sensible defaults for each platform in `svgToPdf`. In particular I'd prefer it to work out of the box on OSX.

Do you think the solution in 3f3664e is adequate?

**Comment by svenkeidel** [comment]
I test your implementation this evening. I'm currently using Linux, so we can test on two operating systems. How about some unit tests?

**Comment by kaoskorobase** [comment]
Sure, highly welcome! I'll configure the project for building and testing on Travis CI.
